interface colorStruct {
  background: string;
  hoverColor: string;
  border: string;
  outlineBorder: string;
  text: string;
  outlineText: string;
  icon: string;
  outlineIcon: string;
  focus: string;
}

export const colorMap: { [key: string]: colorStruct } = {
  red: {
    background: "bg-red-600",
    hoverColor: "hover:bg-red-700",
    border: "border-white",
    outlineBorder: "border-red-600",
    text: "text-white",
    outlineText: "text-red-600",
    icon: "white",
    outlineIcon: "red",
    focus: "focus:outline-white",
  },
  green: {
    background: "bg-green-600",
    hoverColor: "hover:bg-green-700",
    border: "border-white",
    outlineBorder: "border-green-600",
    text: "text-white",
    outlineText: "text-green-600",
    icon: "white",
    outlineIcon: "green",
    focus: "focus:outline-white",
  },
  "grey-lighten-4": {
    background: "bg-gray-500",
    hoverColor: "hover:bg-gray-600",
    border: "border-black",
    outlineBorder: "border-gray-500",
    text: "text-black",
    outlineText: "text-gray-500",
    icon: "black",
    outlineIcon: "gray",
    focus: "focus:outline-white",
  },
  "light-green": {
    background: "bg-lime-500",
    hoverColor: "hover:bg-lime-600",
    border: "border-white",
    outlineBorder: "border-lime-500",
    text: "text-white",
    outlineText: "text-lime-500",
    icon: "white",
    outlineIcon: "lime",
    focus: "focus:outline-white",
  },
  lime: {
    background: "bg-lime-400",
    hoverColor: "hover:bg-lime-500",
    border: "border-white",
    outlineBorder: "border-lime-400",
    text: "text-black",
    outlineText: "text-lime-400",
    icon: "black",
    outlineIcon: "lime",
    focus: "focus:outline-black",
  },
  amber: {
    background: "bg-amber-500",
    hoverColor: "hover:bg-amber-600",
    border: "border-white",
    outlineBorder: "border-amber-500",
    text: "text-black",
    outlineText: "text-amber-500",
    icon: "black",
    outlineIcon: "amber",
    focus: "focus:outline-black",
  },
  orange: {
    background: "bg-orange-500",
    hoverColor: "hover:bg-orange-600",
    border: "border-white",
    outlineBorder: "border-orange-500",
    text: "text-black",
    outlineText: "text-orange-500",
    icon: "black",
    outlineIcon: "orange",
    focus: "focus:outline-black",
  },
  "deep-orange": {
    background: "bg-orange-700",
    hoverColor: "hover:bg-orange-800",
    border: "border-white",
    outlineBorder: "border-orange-700",
    text: "text-white",
    outlineText: "text-orange-700",
    icon: "white",
    outlineIcon: "orange",
    focus: "focus:outline-white",
  },
  brown: {
    background: "bg-amber-900",
    hoverColor: "hover:bg-amber-950",
    border: "border-white",
    outlineBorder: "border-amber-900",
    text: "text-white",
    outlineText: "text-amber-900",
    icon: "white",
    outlineIcon: "amber",
    focus: "focus:outline-white",
  },
  "blue-grey": {
    background: "bg-gray-700",
    hoverColor: "hover:bg-gray-800",
    border: "border-white",
    outlineBorder: "border-gray-700",
    text: "text-white",
    outlineText: "text-gray-700",
    icon: "white",
    outlineIcon: "gray",
    focus: "focus:outline-white",
  },
  white: {
    background: "bg-white",
    hoverColor: "hover:bg-gray-100",
    border: "border-black",
    outlineBorder: "border-white",
    text: "text-black",
    outlineText: "text-white",
    icon: "black",
    outlineIcon: "white",
    focus: "focus:outline-black",
  },
  black: {
    background: "bg-black",
    hoverColor: "hover:bg-gray-900",
    border: "border-white",
    outlineBorder: "border-black",
    text: "text-white",
    outlineText: "text-black",
    icon: "white",
    outlineIcon: "black",
    focus: "focus:outline-white",
  },
  blue: {
    background: "bg-blue-600",
    hoverColor: "hover:bg-blue-700",
    border: "border-white",
    outlineBorder: "border-blue-600",
    text: "text-white",
    outlineText: "text-blue-600",
    icon: "white",
    outlineIcon: "blue",
    focus: "focus:outline-white",
  },
};
